# Generated by Django 5.0.4 on 2024-04-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loginuser',
            managers=[
            ],
        ),
    ]
